commands:
move_grippers(opening, opening) 
move_arms(cand, cand)
move_arms(premach1, preload)
move_arms(mach1, load)  
move_grippers(closing, closing)
move_arms(premach1, preload) 
move_arms(cand, premach2)
move_arms(cand, mach2)
move_gripper_2(opening)
move_arms(trans1, premach2)
move_arm_2(cand)
move_arm_2(pretrans2)
move_arm_2(trans2)
move_gripper_2(closing)
move_gripper_1(opening)
move_arm_2(posttrans2)
move_arms(cand, cand)
move_arms(ready_tight_spot,preload)
move_arms(tight_spot,load)
move_grippers(closing,opening)
move_arms(posttight_spot_pickA, preload)
move_arms(posttight_spot_pickB, premach2)
move_arms(premach1, mach2)
move_gripper_2(closing)
move_arms(mach1, premach2)
move_gripper_1(opening)
move_arms(cand, prepick_rob2)
move_arms(prepick_rob1, pick_rob2)
move_gripper_2(opening)
rospy.sleep(1.5) # This is just to wait for the ball to roll. Can be longer if necessary.
move_arms(pick_rob1, prepick_rob2)
move_gripper_1(closing)
move_arm_1(ready_tight_spot)
move_arm_1(pretight_spot_place)
move_arm_1(tight_spot)
move_gripper_1(opening)
move_arm_1(posttight_spot_place)
move_arm_1(ready_tight_spot)
move_arms(cand,cand)